import { AppThemeDefinition } from '../types';

export const bodybuildingTheme: AppThemeDefinition = {
  id: 'bodybuilding',
  name: 'bodybuilding',
  displayName: 'MAROMBA MODE',
  description: {
    en: 'Old school iron paradise. No excuses, only gains.',
    'pt-BR': 'Paraíso do ferro old school. Sem desculpas, só resultado.',
  },
  emoji: '🏋️',
  dashboardIcon: 'barbell',
  tags: ['gym', 'bodybuilding', 'classic', 'intense'],
  locked: false,
  colors: {
    background: '#0A0A0A',
    surface: '#141414',
    surfaceElevated: '#1E1E1E',
    surfaceCard: '#181818',
    border: '#FFD70033',
    borderLight: '#FFD70055',
    primary: '#FFD700',
    primaryLight: '#FFE44D',
    primaryDark: '#CC9900',
    primaryGlow: 'rgba(255,215,0,0.3)',
    secondary: '#FF0000',
    secondaryLight: '#FF4444',
    secondaryGlow: 'rgba(255,0,0,0.25)',
    accent: '#FF6600',
    accentLight: '#FF9933',
    text: {
      primary: '#FFFFFF',
      secondary: '#CCCCCC',
      muted: '#666666',
      onPrimary: '#0A0A0A',
      onDark: '#FFFFFF',
    },
    macros: {
      calories: '#FF0000',
      protein: '#FFD700',
      carbs: '#FF6600',
      fat: '#CC9900',
      fiber: '#00AA44',
    },
    status: {
      success: '#00AA44',
      successLight: '#00CC55',
      warning: '#FF6600',
      warningLight: '#FF9933',
      error: '#CC0000',
      errorLight: '#FF3333',
      info: '#0066CC',
    },
    tabBar: '#141414',
    tabBarActive: '#FFD700',
    tabBarInactive: '#666666',
    inputBackground: '#1E1E1E',
    inputBorder: '#FFD70033',
    gradient: ['#0A0A0A', '#1A1000', '#0A0A0A'] as const,
    overlay: 'rgba(0,0,0,0.8)',
    glow: 'rgba(255,215,0,0.5)',
    sodium: '#FF6600',
    water: '#0066CC',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    en: {
      greeting: [
        "You miss 100% of the gains you don't eat.",
        "LET'S GOOOOO! Time to eat BIG!",
        'The weights are waiting. So is your meal plan.',
        "No pain, no protein. Let's track.",
      ],
      proteinGoalReached: [
        'PROTEIN: CHECKED. GAINS: INCOMING.',
        'Your muscles are smiling, bro.',
        'ANABOLIC WINDOW SECURED! PROTEIN GOAL CRUSHED!',
      ],
      calorieGoalReached: [
        'CALORIC MISSION COMPLETE. TODAY WAS A WIN.',
        'Calories hit. Recovery mode activated.',
        'EAT BIG, LIFT BIG, GET BIG. One step done.',
      ],
      calorieSurplus: [
        'DIRTY BULK ACTIVATED. THE GAINS MUST FLOW.',
        'Caloric surplus achieved. Time to GROW.',
        'MASS MONSTER MODE ENGAGED.',
      ],
      calorieDeficit: [
        'CUT PHASE. SUFFER NOW, SHRED LATER.',
        'Deficit noted. Abs are made in the kitchen.',
        'Leaning out. Stay disciplined, king.',
      ],
      mealAdded: [
        'MEAL LOGGED, BRO.',
        'Gains recorded.',
        'Entry noted. Keep eating.',
        'FUEL ADDED.',
      ],
      streakCongrats: [
        'CONSISTENT! THE MOST UNDERRATED THING IN FITNESS.',
        'Streak alive. Champions are made daily.',
        'EVERY. SINGLE. DAY. That\'s the difference.',
      ],
      noDataYet: [
        "BRO. You haven't eaten yet? The gym won't fuel itself.",
        'Empty log. Start eating and tracking.',
        'No data? No gains. Log your first meal.',
      ],
      goodMorning: [
        'Morning! Break the fast. Protein first.',
        'RISE AND GRIND. Morning fuel time.',
        "Early bird gets the gains. Let's go.",
      ],
      goodAfternoon: [
        "Midday. How's the bulk going?",
        'Afternoon check-in. Keep the macros up.',
        'Post-workout window? Hit that protein.',
      ],
      goodEvening: [
        'Evening. Final macros of the day.',
        'Dinner time. Hit your protein.',
        "Day nearly done. Don't miss your macros.",
      ],
      goodNight: [
        'Rest day or not, eat your protein before sleep.',
        'Good night. Sleep is when the gains happen.',
        'Recovery time. You earned it.',
      ],
      dashboardTitle: 'GYM STATS',
      diaryTitle: 'MEAL LOG',
      progressTitle: 'PROGRESS',
      profileTitle: 'MY STATS',
      settingsTitle: 'SETTINGS',
      caloriesLabel: 'CALORIES',
      proteinLabel: 'PROTEIN',
      carbsLabel: 'CARBS',
      fatLabel: 'FATS',
      fiberLabel: 'FIBER',
      remainingLabel: 'REMAINING',
      consumedLabel: 'CONSUMED',
      goalLabel: 'GOAL',
      addFoodLabel: 'ADD MEAL',
      scanLabel: 'SCAN BARCODE',
      searchLabel: 'SEARCH FOOD',
      macroSectionTitle: '💪 MACROS',
      microSectionTitle: '🔬 MICRONUTRIENTS',
      statsSectionTitle: '📊 DAILY STATS',
      mealNames: {
        BREAKFAST: 'BREAKFAST',
        LUNCH: 'LUNCH',
        DINNER: 'DINNER',
        SNACK: 'SNACK',
      },
    },
    'pt-BR': {
      greeting: [
        'Você perde 100% dos ganhos que não come.',
        'BORAAAA! Hora de comer GRANDE!',
        'Os pesos estão esperando. Seu plano alimentar também.',
        'Sem dor, sem proteína. Vamos registrar.',
      ],
      proteinGoalReached: [
        'PROTEÍNA: CONFERIDA. GANHOS: A CAMINHO.',
        'Seus músculos estão sorrindo, mano.',
        'JANELA ANABÓLICA GARANTIDA! META DE PROTEÍNA ESMAGADA!',
      ],
      calorieGoalReached: [
        'MISSÃO CALÓRICA COMPLETA. HOJE FOI VITÓRIA.',
        'Calorias batidas. Modo recuperação ativado.',
        'COMA GRANDE, LEVANTE GRANDE, FIQUE GRANDE. Mais um passo dado.',
      ],
      calorieSurplus: [
        'BULKING SUJO ATIVADO. OS GANHOS PRECISAM FLUIR.',
        'Excedente calórico alcançado. Hora de CRESCER.',
        'MODO MONSTRO DE MASSA ATIVADO.',
      ],
      calorieDeficit: [
        'FASE DE CORTE. SOFRA AGORA, DEFINA DEPOIS.',
        'Déficit registrado. Abdômen se faz na cozinha.',
        'Secando. Mantenha a disciplina, rei.',
      ],
      mealAdded: [
        'REFEIÇÃO REGISTRADA, MANO.',
        'Ganhos registrados.',
        'Entrada anotada. Continue comendo.',
        'COMBUSTÍVEL ADICIONADO.',
      ],
      streakCongrats: [
        'CONSISTENTE! A COISA MAIS SUBESTIMADA DO FITNESS.',
        'Sequência viva. Campeões se fazem todo dia.',
        'TODOS. OS. DIAS. Essa é a diferença.',
      ],
      noDataYet: [
        'MANO. Você ainda não comeu? A academia não se alimenta sozinha.',
        'Registro vazio. Comece a comer e registrar.',
        'Sem dado? Sem ganho. Registre sua primeira refeição.',
      ],
      goodMorning: [
        'Bom dia! Quebre o jejum. Proteína primeiro.',
        'ACORDE E TREINE. Hora do combustível matinal.',
        'Quem madruga pega os ganhos. Vamos lá.',
      ],
      goodAfternoon: [
        'Meio-dia. Como está indo o bulking?',
        'Check-in da tarde. Mantenha os macros em dia.',
        'Janela pós-treino? Manda ver na proteína.',
      ],
      goodEvening: [
        'Noite. Últimos macros do dia.',
        'Hora do jantar. Bata sua proteína.',
        'Dia quase acabando. Não perca seus macros.',
      ],
      goodNight: [
        'Dia de descanso ou não, coma proteína antes de dormir.',
        'Boa noite. Dormir é quando os ganhos acontecem.',
        'Hora de recuperar. Você merece.',
      ],
      dashboardTitle: 'STATUS DA ACADEMIA',
      diaryTitle: 'REGISTRO DE REFEIÇÕES',
      progressTitle: 'PROGRESSO',
      profileTitle: 'MEUS STATUS',
      settingsTitle: 'CONFIGURAÇÕES',
      caloriesLabel: 'CALORIAS',
      proteinLabel: 'PROTEÍNA',
      carbsLabel: 'CARBOIDRATOS',
      fatLabel: 'GORDURAS',
      fiberLabel: 'FIBRA',
      remainingLabel: 'RESTANTE',
      consumedLabel: 'CONSUMIDO',
      goalLabel: 'META',
      addFoodLabel: 'ADICIONAR REFEIÇÃO',
      scanLabel: 'ESCANEAR CÓDIGO',
      searchLabel: 'BUSCAR ALIMENTO',
      macroSectionTitle: '💪 MACROS',
      microSectionTitle: '🔬 MICRONUTRIENTES',
      statsSectionTitle: '📊 STATUS DIÁRIOS',
      mealNames: {
        BREAKFAST: 'CAFÉ DA MANHÃ',
        LUNCH: 'ALMOÇO',
        DINNER: 'JANTAR',
        SNACK: 'LANCHE',
      },
    },
  },
  companion: {
    id: 'coach',
    name: 'The Coach',
    title: {
      en: 'Old School Iron Sage',
      'pt-BR': 'O Sábio do Ferro Old School',
    },
    description: {
      en: 'Built in the 70s golden era. Has seen every fad diet and every champion. Respects only consistency and compound lifts.',
      'pt-BR': 'Forjado na era de ouro dos anos 70. Já viu toda dieta da moda e todo campeão. Só respeita consistência e levantamentos compostos.',
    },
    emoji: '🏋️',
    avatarEmoji: '💪',
    personality: 'intense',
    accentColor: '#FFD700',
    bubbleColor: '#181818',
    textColor: '#FFFFFF',
  },
};
