import { AppTheme } from '../types';

export const bodybuildingTheme: AppTheme = {
  id: 'bodybuilding',
  name: 'bodybuilding',
  displayName: 'MAROMBA MODE',
  description: 'Old school iron paradise. No excuses, only gains.',
  emoji: '🏋️',
  tags: ['gym', 'bodybuilding', 'classic', 'intense'],
  locked: false,
  colors: {
    background: '#0A0A0A',
    surface: '#141414',
    surfaceElevated: '#1E1E1E',
    surfaceCard: '#181818',
    border: '#FFD70033',
    borderLight: '#FFD70055',
    primary: '#FFD700',
    primaryLight: '#FFE44D',
    primaryDark: '#CC9900',
    primaryGlow: 'rgba(255,215,0,0.3)',
    secondary: '#FF0000',
    secondaryLight: '#FF4444',
    secondaryGlow: 'rgba(255,0,0,0.25)',
    accent: '#FF6600',
    accentLight: '#FF9933',
    text: {
      primary: '#FFFFFF',
      secondary: '#CCCCCC',
      muted: '#666666',
      onPrimary: '#0A0A0A',
      onDark: '#FFFFFF',
    },
    macros: {
      calories: '#FF0000',
      protein: '#FFD700',
      carbs: '#FF6600',
      fat: '#CC9900',
      fiber: '#00AA44',
    },
    status: {
      success: '#00AA44',
      successLight: '#00CC55',
      warning: '#FF6600',
      warningLight: '#FF9933',
      error: '#CC0000',
      errorLight: '#FF3333',
      info: '#0066CC',
    },
    tabBar: '#141414',
    tabBarActive: '#FFD700',
    tabBarInactive: '#666666',
    inputBackground: '#1E1E1E',
    inputBorder: '#FFD70033',
    gradient: ['#0A0A0A', '#1A1000', '#0A0A0A'] as const,
    overlay: 'rgba(0,0,0,0.8)',
    glow: 'rgba(255,215,0,0.5)',
    sodium: '#FF6600',
    water: '#0066CC',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      "You miss 100% of the gains you don't eat.",
      "LET'S GOOOOO! Time to eat BIG!",
      'The weights are waiting. So is your meal plan.',
      'No pain, no protein. Let\'s track.',
    ],
    proteinGoalReached: [
      'PROTEIN: CHECKED. GAINS: INCOMING.',
      'Your muscles are smiling, bro.',
      'ANABOLIC WINDOW SECURED! PROTEIN GOAL CRUSHED!',
    ],
    calorieGoalReached: [
      'CALORIC MISSION COMPLETE. TODAY WAS A WIN.',
      'Calories hit. Recovery mode activated.',
      'EAT BIG, LIFT BIG, GET BIG. One step done.',
    ],
    calorieSurplus: [
      'DIRTY BULK ACTIVATED. THE GAINS MUST FLOW.',
      'Caloric surplus achieved. Time to GROW.',
      'MASS MONSTER MODE ENGAGED.',
    ],
    calorieDeficit: [
      'CUT PHASE. SUFFER NOW, SHRED LATER.',
      'Deficit noted. Abs are made in the kitchen.',
      'Leaning out. Stay disciplined, king.',
    ],
    mealAdded: [
      'MEAL LOGGED, BRO.',
      'Gains recorded.',
      'Entry noted. Keep eating.',
      'FUEL ADDED.',
    ],
    streakCongrats: [
      "CONSISTENT! THE MOST UNDERRATED THING IN FITNESS.",
      "Streak alive. Champions are made daily.",
      "EVERY. SINGLE. DAY. That's the difference.",
    ],
    noDataYet: [
      "BRO. You haven't eaten yet? The gym won't fuel itself.",
      'Empty log. Start eating and tracking.',
      'No data? No gains. Log your first meal.',
    ],
    goodMorning: [
      'Morning! Break the fast. Protein first.',
      'RISE AND GRIND. Morning fuel time.',
      'Early bird gets the gains. Let\'s go.',
    ],
    goodAfternoon: [
      "Midday. How's the bulk going?",
      'Afternoon check-in. Keep the macros up.',
      'Post-workout window? Hit that protein.',
    ],
    goodEvening: [
      'Evening. Final macros of the day.',
      'Dinner time. Hit your protein.',
      "Day nearly done. Don't miss your macros.",
    ],
    goodNight: [
      'Rest day or not, eat your protein before sleep.',
      'Good night. Sleep is when the gains happen.',
      'Recovery time. You earned it.',
    ],
    dashboardTitle: 'GYM STATS',
    diaryTitle: 'MEAL LOG',
    progressTitle: 'PROGRESS',
    profileTitle: 'MY STATS',
    settingsTitle: 'SETTINGS',
    caloriesLabel: 'CALORIES',
    proteinLabel: 'PROTEIN',
    carbsLabel: 'CARBS',
    fatLabel: 'FATS',
    fiberLabel: 'FIBER',
    remainingLabel: 'REMAINING',
    consumedLabel: 'CONSUMED',
    goalLabel: 'GOAL',
    addFoodLabel: 'ADD MEAL',
    scanLabel: 'SCAN BARCODE',
    searchLabel: 'SEARCH FOOD',
    macroSectionTitle: '💪 MACROS',
    microSectionTitle: '🔬 MICRONUTRIENTS',
    statsSectionTitle: '📊 DAILY STATS',
    mealNames: {
      BREAKFAST: 'BREAKFAST',
      LUNCH: 'LUNCH',
      DINNER: 'DINNER',
      SNACK: 'SNACK',
    },
  },
  companion: {
    id: 'coach',
    name: 'The Coach',
    title: 'Old School Iron Sage',
    description: "Built in the 70s golden era. Has seen every fad diet and every champion. Respects only consistency and compound lifts.",
    emoji: '🏋️',
    avatarEmoji: '💪',
    personality: 'intense',
    accentColor: '#FFD700',
    bubbleColor: '#181818',
    textColor: '#FFFFFF',
  },
};
