import { AppThemeDefinition } from '../types';

export const darkFantasyTheme: AppThemeDefinition = {
  id: 'dark-fantasy',
  name: 'dark-fantasy',
  displayName: 'Dark Fantasy',
  description: {
    en: 'Count calories in the shadow realm. The Necromancer guides your macros.',
    'pt-BR': 'Conte calorias no reino das sombras. O Necromante guia seus macros.',
  },
  emoji: '💀',
  dashboardIcon: 'skull',
  tags: ['dark', 'gothic'],
  locked: false,
  colors: {
    background: '#0A0A0F',
    surface: '#12121A',
    surfaceElevated: '#1A1A28',
    surfaceCard: '#16161F',
    border: '#2A1A2A',
    borderLight: '#3A2A3A',
    primary: '#8B1A1A',
    primaryLight: '#C62828',
    primaryDark: '#5A0A0A',
    primaryGlow: 'rgba(139, 26, 26, 0.3)',
    secondary: '#C9A84C',
    secondaryLight: '#E8C87A',
    secondaryGlow: 'rgba(201, 168, 76, 0.2)',
    accent: '#5A2D6B',
    accentLight: '#8B4DA8',
    text: {
      primary: '#E8D5C4',
      secondary: '#9E8575',
      muted: '#5A4A3A',
      onPrimary: '#F0E8E0',
      onDark: '#E8D5C4',
    },
    macros: {
      calories: '#C62828',
      protein: '#9B3D9B',
      carbs: '#A0522D',
      fat: '#B8860B',
      fiber: '#2E8B57',
    },
    status: {
      success: '#2E7D32',
      successLight: '#4CAF50',
      warning: '#E65100',
      warningLight: '#FF7043',
      error: '#8B0000',
      errorLight: '#C62828',
      info: '#1565C0',
    },
    tabBar: '#12121A',
    tabBarActive: '#C62828',
    tabBarInactive: '#5A4A3A',
    inputBackground: '#1A1A28',
    inputBorder: '#2A1A2A',
    gradient: ['#0A0A0F', '#1A0A0A', '#0A0A0F'] as const,
    overlay: 'rgba(0,0,0,0.7)',
    glow: 'rgba(139,26,26,0.4)',
    gold: '#C9A84C',
    goldGlow: 'rgba(201,168,76,0.2)',
    sodium: '#FF6F00',
    water: '#1565C0',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    en: {
      greeting: [
        'The archives await your offering.',
        'What darkness shall you consume today?',
        'The void hungers. Feed it wisely.',
        'Another soul seeks sustenance.',
      ],
      proteinGoalReached: [
        'The flesh grows stronger. The ritual is complete.',
        'Your gains have been recorded in the Tome of Power.',
        'Protein quota fulfilled. The necromancer nods approvingly.',
      ],
      calorieGoalReached: [
        'The daily sacrifice is complete.',
        'Caloric ritual concluded. The shadows recede.',
        'Another day of sustenance. The curse persists.',
      ],
      calorieSurplus: [
        'The gluttony grows. The dark gods are pleased.',
        'Excess consumed. The curse strengthens.',
        'You have fed beyond the ritual requirements.',
      ],
      calorieDeficit: [
        'The void consumes what flesh does not.',
        'Cutting phase active. The suffering is intentional.',
        'Caloric restraint noted in the ancient tome.',
      ],
      mealAdded: [
        'Offering recorded.',
        'The flesh receives its tribute.',
        'Entry inscribed in the dark tome.',
        'Sustenance logged.',
      ],
      streakCongrats: [
        'Consistency. The most powerful dark magic.',
        'The ritual continues unbroken.',
        'Your devotion to the dark arts of nutrition grows.',
      ],
      noDataYet: [
        'The tome is empty. Begin the ritual.',
        'No offerings yet. The void awaits.',
        'Your journey of suffering has not begun.',
      ],
      goodMorning: [
        'Dawn rations await, wanderer.',
        'The void consumes the night. Rise and feed.',
        'A new day of suffering begins.',
      ],
      goodAfternoon: [
        'Midday sustenance approaches.',
        'The sun reaches its zenith. Feed the ritual.',
        'Afternoon. The dark work continues.',
      ],
      goodEvening: [
        'Nightly feast approaches.',
        'The shadows lengthen. Final offerings of the day.',
        'Dusk rations. Make them count.',
      ],
      goodNight: [
        'The darkness deepens. Rest, wanderer.',
        'The void consumes the night once more.',
        'Sleep. Tomorrow the suffering resumes.',
      ],
      dashboardTitle: 'THE SANCTUM',
      diaryTitle: 'DARK TOME',
      progressTitle: 'THE CHRONICLE',
      profileTitle: 'THE SOUL',
      settingsTitle: 'THE ARCANE',
      caloriesLabel: 'SACRIFICED',
      proteinLabel: 'FLESH',
      carbsLabel: 'CURSED CARBS',
      fatLabel: 'DARK FAT',
      fiberLabel: 'ANCIENT FIBER',
      remainingLabel: 'REMAINING DARK ENERGY',
      consumedLabel: 'CONSUMED',
      goalLabel: 'THE RITUAL DEMANDS',
      addFoodLabel: 'ADD OFFERING',
      scanLabel: 'SCAN THE RUNE',
      searchLabel: 'SEEK IN THE VOID',
      macroSectionTitle: '⚔️ MACRO WARFARE',
      microSectionTitle: '💀 MICRONUTRIENT DESPAIR',
      statsSectionTitle: '📊 SUFFERING STATISTICS',
      mealNames: {
        BREAKFAST: 'DAWN RATIONS',
        LUNCH: 'MIDDAY OFFERING',
        DINNER: 'NIGHTLY FEAST',
        SNACK: 'CURSED MORSELS',
      },
    },
    'pt-BR': {
      greeting: [
        'Os arquivos aguardam sua oferenda.',
        'Que escuridão você consumirá hoje?',
        'O vazio tem fome. Alimente-o com sabedoria.',
        'Outra alma busca sustento.',
      ],
      proteinGoalReached: [
        'A carne se fortalece. O ritual está completo.',
        'Seus ganhos foram registrados no Tomo do Poder.',
        'Cota de proteína cumprida. O necromante acena em aprovação.',
      ],
      calorieGoalReached: [
        'O sacrifício diário está completo.',
        'Ritual calórico concluído. As sombras recuam.',
        'Mais um dia de sustento. A maldição persiste.',
      ],
      calorieSurplus: [
        'A gula cresce. Os deuses sombrios estão satisfeitos.',
        'Excesso consumido. A maldição se fortalece.',
        'Você se alimentou além das exigências do ritual.',
      ],
      calorieDeficit: [
        'O vazio consome o que a carne não consome.',
        'Fase de corte ativa. O sofrimento é intencional.',
        'Restrição calórica registrada no tomo antigo.',
      ],
      mealAdded: [
        'Oferenda registrada.',
        'A carne recebe seu tributo.',
        'Entrada inscrita no tomo sombrio.',
        'Sustento registrado.',
      ],
      streakCongrats: [
        'Consistência. A mais poderosa magia sombria.',
        'O ritual continua ininterrupto.',
        'Sua devoção às artes sombrias da nutrição cresce.',
      ],
      noDataYet: [
        'O tomo está vazio. Comece o ritual.',
        'Nenhuma oferenda ainda. O vazio aguarda.',
        'Sua jornada de sofrimento ainda não começou.',
      ],
      goodMorning: [
        'A ração da alvorada aguarda, andarilho.',
        'O vazio consome a noite. Levante-se e alimente-se.',
        'Um novo dia de sofrimento começa.',
      ],
      goodAfternoon: [
        'O sustento do meio-dia se aproxima.',
        'O sol atinge seu zênite. Alimente o ritual.',
        'Tarde. O trabalho sombrio continua.',
      ],
      goodEvening: [
        'O festim noturno se aproxima.',
        'As sombras se alongam. Últimas oferendas do dia.',
        'Ração do crepúsculo. Faça-a valer.',
      ],
      goodNight: [
        'A escuridão se aprofunda. Descanse, andarilho.',
        'O vazio consome a noite mais uma vez.',
        'Durma. Amanhã o sofrimento recomeça.',
      ],
      dashboardTitle: 'O SANTUÁRIO',
      diaryTitle: 'TOMO SOMBRIO',
      progressTitle: 'A CRÔNICA',
      profileTitle: 'A ALMA',
      settingsTitle: 'O ARCANO',
      caloriesLabel: 'SACRIFICADAS',
      proteinLabel: 'CARNE',
      carbsLabel: 'CARBOS AMALDIÇOADOS',
      fatLabel: 'GORDURA SOMBRIA',
      fiberLabel: 'FIBRA ANCESTRAL',
      remainingLabel: 'ENERGIA SOMBRIA RESTANTE',
      consumedLabel: 'CONSUMIDO',
      goalLabel: 'O RITUAL EXIGE',
      addFoodLabel: 'ADICIONAR OFERENDA',
      scanLabel: 'ESCANEAR A RUNA',
      searchLabel: 'BUSCAR NO VAZIO',
      macroSectionTitle: '⚔️ GUERRA DOS MACROS',
      microSectionTitle: '💀 DESESPERO DOS MICRONUTRIENTES',
      statsSectionTitle: '📊 ESTATÍSTICAS DO SOFRIMENTO',
      mealNames: {
        BREAKFAST: 'RAÇÃO DA ALVORADA',
        LUNCH: 'OFERENDA DO MEIO-DIA',
        DINNER: 'FESTIM NOTURNO',
        SNACK: 'PETISCOS AMALDIÇOADOS',
      },
    },
  },
  companion: {
    id: 'necromancer',
    name: 'The Necromancer',
    title: {
      en: 'Keeper of the Dark Tome',
      'pt-BR': 'Guardião do Tomo Sombrio',
    },
    description: {
      en: 'Ancient keeper of nutritional secrets. Judges your macros from beyond the veil.',
      'pt-BR': 'Antigo guardião dos segredos nutricionais. Julga seus macros além do véu.',
    },
    emoji: '🧙‍♂️',
    avatarEmoji: '💀',
    personality: 'dark',
    accentColor: '#C9A84C',
    bubbleColor: '#16161F',
    textColor: '#E8D5C4',
  },
};
