import { AppTheme } from '../types';

export const darkFantasyTheme: AppTheme = {
  id: 'dark-fantasy',
  name: 'dark-fantasy',
  displayName: 'Dark Fantasy',
  description: 'Count calories in the shadow realm. The Necromancer guides your macros.',
  emoji: '💀',
  tags: ['dark', 'gothic', 'default'],
  locked: false,
  colors: {
    background: '#0A0A0F',
    surface: '#12121A',
    surfaceElevated: '#1A1A28',
    surfaceCard: '#16161F',
    border: '#2A1A2A',
    borderLight: '#3A2A3A',
    primary: '#8B1A1A',
    primaryLight: '#C62828',
    primaryDark: '#5A0A0A',
    primaryGlow: 'rgba(139, 26, 26, 0.3)',
    secondary: '#C9A84C',
    secondaryLight: '#E8C87A',
    secondaryGlow: 'rgba(201, 168, 76, 0.2)',
    accent: '#5A2D6B',
    accentLight: '#8B4DA8',
    text: {
      primary: '#E8D5C4',
      secondary: '#9E8575',
      muted: '#5A4A3A',
      onPrimary: '#F0E8E0',
      onDark: '#E8D5C4',
    },
    macros: {
      calories: '#C62828',
      protein: '#9B3D9B',
      carbs: '#A0522D',
      fat: '#B8860B',
      fiber: '#2E8B57',
    },
    status: {
      success: '#2E7D32',
      successLight: '#4CAF50',
      warning: '#E65100',
      warningLight: '#FF7043',
      error: '#8B0000',
      errorLight: '#C62828',
      info: '#1565C0',
    },
    tabBar: '#12121A',
    tabBarActive: '#C62828',
    tabBarInactive: '#5A4A3A',
    inputBackground: '#1A1A28',
    inputBorder: '#2A1A2A',
    gradient: ['#0A0A0F', '#1A0A0A', '#0A0A0F'] as const,
    overlay: 'rgba(0,0,0,0.7)',
    glow: 'rgba(139,26,26,0.4)',
    gold: '#C9A84C',
    goldGlow: 'rgba(201,168,76,0.2)',
    sodium: '#FF6F00',
    water: '#1565C0',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      'The archives await your offering.',
      'What darkness shall you consume today?',
      'The void hungers. Feed it wisely.',
      'Another soul seeks sustenance.',
    ],
    proteinGoalReached: [
      'The flesh grows stronger. The ritual is complete.',
      'Your gains have been recorded in the Tome of Power.',
      'Protein quota fulfilled. The necromancer nods approvingly.',
    ],
    calorieGoalReached: [
      'The daily sacrifice is complete.',
      'Caloric ritual concluded. The shadows recede.',
      'Another day of sustenance. The curse persists.',
    ],
    calorieSurplus: [
      'The gluttony grows. The dark gods are pleased.',
      'Excess consumed. The curse strengthens.',
      'You have fed beyond the ritual requirements.',
    ],
    calorieDeficit: [
      'The void consumes what flesh does not.',
      'Cutting phase active. The suffering is intentional.',
      'Caloric restraint noted in the ancient tome.',
    ],
    mealAdded: [
      'Offering recorded.',
      'The flesh receives its tribute.',
      'Entry inscribed in the dark tome.',
      'Sustenance logged.',
    ],
    streakCongrats: [
      'Consistency. The most powerful dark magic.',
      'The ritual continues unbroken.',
      'Your devotion to the dark arts of nutrition grows.',
    ],
    noDataYet: [
      'The tome is empty. Begin the ritual.',
      'No offerings yet. The void awaits.',
      'Your journey of suffering has not begun.',
    ],
    goodMorning: [
      'Dawn rations await, wanderer.',
      'The void consumes the night. Rise and feed.',
      'A new day of suffering begins.',
    ],
    goodAfternoon: [
      'Midday sustenance approaches.',
      'The sun reaches its zenith. Feed the ritual.',
      'Afternoon. The dark work continues.',
    ],
    goodEvening: [
      'Nightly feast approaches.',
      'The shadows lengthen. Final offerings of the day.',
      'Dusk rations. Make them count.',
    ],
    goodNight: [
      'The darkness deepens. Rest, wanderer.',
      'The void consumes the night once more.',
      'Sleep. Tomorrow the suffering resumes.',
    ],
    dashboardTitle: 'THE SANCTUM',
    diaryTitle: 'DARK TOME',
    progressTitle: 'THE CHRONICLE',
    profileTitle: 'THE SOUL',
    settingsTitle: 'THE ARCANE',
    caloriesLabel: 'SACRIFICED',
    proteinLabel: 'FLESH',
    carbsLabel: 'CURSED CARBS',
    fatLabel: 'DARK FAT',
    fiberLabel: 'ANCIENT FIBER',
    remainingLabel: 'REMAINING DARK ENERGY',
    consumedLabel: 'CONSUMED',
    goalLabel: 'THE RITUAL DEMANDS',
    addFoodLabel: 'ADD OFFERING',
    scanLabel: 'SCAN THE RUNE',
    searchLabel: 'SEEK IN THE VOID',
    macroSectionTitle: '⚔️ MACRO WARFARE',
    microSectionTitle: '💀 MICRONUTRIENT DESPAIR',
    statsSectionTitle: '📊 SUFFERING STATISTICS',
    mealNames: {
      BREAKFAST: 'DAWN RATIONS',
      LUNCH: 'MIDDAY OFFERING',
      DINNER: 'NIGHTLY FEAST',
      SNACK: 'CURSED MORSELS',
    },
  },
  companion: {
    id: 'necromancer',
    name: 'The Necromancer',
    title: 'Keeper of the Dark Tome',
    description: 'Ancient keeper of nutritional secrets. Judges your macros from beyond the veil.',
    emoji: '🧙‍♂️',
    avatarEmoji: '💀',
    personality: 'dark',
    accentColor: '#C9A84C',
    bubbleColor: '#16161F',
    textColor: '#E8D5C4',
  },
};
