import { AppThemeDefinition } from '../types';

export const vanillaTheme: AppThemeDefinition = {
  id: 'vanilla',
  name: 'vanilla',
  displayName: 'Vanilla',
  description: {
    en: 'The classic experience. Clean, modern, distraction-free — just your macros.',
    'pt-BR': 'A experiência clássica. Limpa, moderna e sem distrações — só seus macros.',
  },
  emoji: '✨',
  dashboardIcon: 'stats-chart',
  tags: ['dark', 'minimal', 'default'],
  locked: false,
  colors: {
    background: '#0B0F14',
    surface: '#131820',
    surfaceElevated: '#1A212B',
    surfaceCard: '#161C25',
    border: '#232B36',
    borderLight: '#2E3947',
    primary: '#0EA5E9',
    primaryLight: '#38BDF8',
    primaryDark: '#0369A1',
    primaryGlow: 'rgba(14,165,233,0.25)',
    secondary: '#10B981',
    secondaryLight: '#34D399',
    secondaryGlow: 'rgba(16,185,129,0.2)',
    accent: '#818CF8',
    accentLight: '#A5B4FC',
    text: {
      primary: '#E2E8F0',
      secondary: '#94A3B8',
      muted: '#64748B',
      onPrimary: '#FFFFFF',
      onDark: '#E2E8F0',
    },
    macros: {
      calories: '#F87171',
      protein: '#A78BFA',
      carbs: '#FBBF24',
      fat: '#38BDF8',
      fiber: '#34D399',
    },
    status: {
      success: '#22C55E',
      successLight: '#4ADE80',
      warning: '#F59E0B',
      warningLight: '#FBBF24',
      error: '#EF4444',
      errorLight: '#F87171',
      info: '#38BDF8',
    },
    tabBar: '#10141B',
    tabBarActive: '#38BDF8',
    tabBarInactive: '#5B6472',
    inputBackground: '#161C25',
    inputBorder: '#2E3947',
    gradient: ['#0B0F14', '#111721', '#0B0F14'] as const,
    overlay: 'rgba(0,0,0,0.6)',
    glow: 'rgba(56,189,248,0.25)',
    sodium: '#FB923C',
    water: '#38BDF8',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    en: {
      greeting: [
        'Good to see you! Ready to track?',
        "Let's make today count.",
        'Your nutrition journey continues.',
        'Time to log your meals!',
      ],
      proteinGoalReached: [
        'Protein goal reached. Great work!',
        'You hit your protein target today!',
        'Excellent! Muscle recovery is on track.',
      ],
      calorieGoalReached: [
        'Calorie goal achieved for today.',
        "You've hit your daily target. Nice job!",
        'Daily nutrition goal complete!',
      ],
      calorieSurplus: [
        "You're over your calorie goal today.",
        'Calorie surplus noted. Adjust tomorrow if needed.',
        'Over goal. Consider lighter meals next time.',
      ],
      calorieDeficit: [
        "You're under your calorie goal today.",
        'Calorie deficit — great for weight loss goals.',
        "You're in a deficit. Stay consistent!",
      ],
      mealAdded: [
        'Logged!',
        'Meal added.',
        'Saved successfully.',
        'Entry recorded.',
      ],
      streakCongrats: [
        "You're on a streak! Keep it up!",
        'Consistency is key — great job!',
        'Another day logged. Excellent habit!',
      ],
      noDataYet: [
        'No meals logged yet. Start tracking!',
        'Ready to log your first meal?',
        'Your diary is empty. Add your first meal!',
      ],
      goodMorning: [
        'Good morning! Start your day right.',
        'Morning! Time for breakfast.',
        'Rise and shine! Log your breakfast.',
      ],
      goodAfternoon: [
        "Good afternoon! How's lunch looking?",
        'Midday check-in. How are your macros?',
        'Afternoon! Keep up the good work.',
      ],
      goodEvening: [
        'Good evening! Wrapping up for the day?',
        'Almost done for the day. Log dinner!',
        "Evening! Don't forget your final meal.",
      ],
      goodNight: [
        'Good night! Rest up.',
        'Time to recover. See you tomorrow!',
        'Great day of tracking. Sleep well!',
      ],
      dashboardTitle: 'Dashboard',
      diaryTitle: 'Food Diary',
      progressTitle: 'Progress',
      profileTitle: 'Profile',
      settingsTitle: 'Settings',
      caloriesLabel: 'Calories',
      proteinLabel: 'Protein',
      carbsLabel: 'Carbs',
      fatLabel: 'Fat',
      fiberLabel: 'Fiber',
      remainingLabel: 'Remaining',
      consumedLabel: 'Consumed',
      goalLabel: 'Goal',
      addFoodLabel: 'Add Food',
      scanLabel: 'Scan Barcode',
      searchLabel: 'Search Foods',
      macroSectionTitle: '📊 Macros',
      microSectionTitle: '🔬 Micronutrients',
      statsSectionTitle: '📈 Daily Stats',
      mealNames: {
        BREAKFAST: 'Breakfast',
        LUNCH: 'Lunch',
        DINNER: 'Dinner',
        SNACK: 'Snack',
      },
    },
    'pt-BR': {
      greeting: [
        'Que bom te ver! Pronto para registrar?',
        'Vamos fazer hoje valer a pena.',
        'Sua jornada nutricional continua.',
        'Hora de registrar suas refeições!',
      ],
      proteinGoalReached: [
        'Meta de proteína atingida. Ótimo trabalho!',
        'Você bateu sua meta de proteína hoje!',
        'Excelente! A recuperação muscular está em dia.',
      ],
      calorieGoalReached: [
        'Meta de calorias atingida hoje.',
        'Você bateu sua meta diária. Bom trabalho!',
        'Meta nutricional do dia completa!',
      ],
      calorieSurplus: [
        'Você passou da meta de calorias hoje.',
        'Excedente de calorias registrado. Ajuste amanhã se precisar.',
        'Acima da meta. Considere refeições mais leves na próxima.',
      ],
      calorieDeficit: [
        'Você está abaixo da meta de calorias hoje.',
        'Déficit calórico — ótimo para metas de emagrecimento.',
        'Você está em déficit. Mantenha a consistência!',
      ],
      mealAdded: [
        'Registrado!',
        'Refeição adicionada.',
        'Salvo com sucesso.',
        'Item registrado.',
      ],
      streakCongrats: [
        'Você está numa sequência! Continue assim!',
        'Consistência é tudo — ótimo trabalho!',
        'Mais um dia registrado. Excelente hábito!',
      ],
      noDataYet: [
        'Nenhuma refeição registrada ainda. Comece agora!',
        'Pronto para registrar sua primeira refeição?',
        'Seu diário está vazio. Adicione sua primeira refeição!',
      ],
      goodMorning: [
        'Bom dia! Comece o dia da forma certa.',
        'Manhã! Hora do café da manhã.',
        'Acorde e brilhe! Registre seu café da manhã.',
      ],
      goodAfternoon: [
        'Boa tarde! Como está o almoço?',
        'Check-in do meio-dia. Como estão seus macros?',
        'Boa tarde! Continue o bom trabalho.',
      ],
      goodEvening: [
        'Boa noite! Fechando o dia?',
        'Quase terminando o dia. Registre o jantar!',
        'Noite! Não esqueça sua última refeição.',
      ],
      goodNight: [
        'Boa noite! Descanse bem.',
        'Hora de recuperar. Até amanhã!',
        'Ótimo dia de registros. Durma bem!',
      ],
      dashboardTitle: 'Painel',
      diaryTitle: 'Diário Alimentar',
      progressTitle: 'Progresso',
      profileTitle: 'Perfil',
      settingsTitle: 'Configurações',
      caloriesLabel: 'Calorias',
      proteinLabel: 'Proteína',
      carbsLabel: 'Carboidratos',
      fatLabel: 'Gordura',
      fiberLabel: 'Fibra',
      remainingLabel: 'Restante',
      consumedLabel: 'Consumido',
      goalLabel: 'Meta',
      addFoodLabel: 'Adicionar Alimento',
      scanLabel: 'Escanear Código',
      searchLabel: 'Buscar Alimentos',
      macroSectionTitle: '📊 Macros',
      microSectionTitle: '🔬 Micronutrientes',
      statsSectionTitle: '📈 Estatísticas Diárias',
      mealNames: {
        BREAKFAST: 'Café da Manhã',
        LUNCH: 'Almoço',
        DINNER: 'Jantar',
        SNACK: 'Lanche',
      },
    },
  },
  companion: {
    id: 'alex',
    name: 'Alex',
    title: {
      en: 'Your Nutrition Coach',
      'pt-BR': 'Seu Treinador Nutricional',
    },
    description: {
      en: 'Friendly, evidence-based nutrition coach. No nonsense, just results.',
      'pt-BR': 'Treinador nutricional amigável e baseado em evidências. Sem enrolação, só resultados.',
    },
    emoji: '👋',
    avatarEmoji: '🥗',
    personality: 'clean',
    accentColor: '#38BDF8',
    bubbleColor: '#161C25',
    textColor: '#E2E8F0',
  },
};
