import { AppThemeDefinition } from '../types';

export const footballTheme: AppThemeDefinition = {
  id: 'football',
  name: 'football',
  displayName: 'Football',
  description: {
    en: 'Fuel like a pro. The Coach is watching your macros.',
    'pt-BR': 'Se alimente como um profissional. O Técnico está de olho nos seus macros.',
  },
  emoji: '⚽',
  dashboardIcon: 'football',
  tags: ['football', 'soccer', 'sport', 'team'],
  locked: false,
  colors: {
    background: '#0A1A0A',
    surface: '#0D200D',
    surfaceElevated: '#142814',
    surfaceCard: '#102010',
    border: '#1E4A1E',
    borderLight: '#2A5E2A',
    primary: '#00AA44',
    primaryLight: '#00CC55',
    primaryDark: '#007733',
    primaryGlow: 'rgba(0,170,68,0.3)',
    secondary: '#FFD700',
    secondaryLight: '#FFE44D',
    secondaryGlow: 'rgba(255,215,0,0.2)',
    accent: '#FFFFFF',
    accentLight: '#F0F0F0',
    text: {
      primary: '#FFFFFF',
      secondary: '#99CC99',
      muted: '#336633',
      onPrimary: '#FFFFFF',
      onDark: '#FFFFFF',
    },
    macros: {
      calories: '#FF4444',
      protein: '#FFD700',
      carbs: '#00CC55',
      fat: '#FF6600',
      fiber: '#00AA44',
    },
    status: {
      success: '#00AA44',
      successLight: '#00CC55',
      warning: '#FFD700',
      warningLight: '#FFE44D',
      error: '#CC0000',
      errorLight: '#FF3333',
      info: '#0066CC',
    },
    tabBar: '#0D200D',
    tabBarActive: '#00AA44',
    tabBarInactive: '#336633',
    inputBackground: '#142814',
    inputBorder: '#1E4A1E',
    gradient: ['#0A1A0A', '#0D200D', '#0A1A0A'] as const,
    overlay: 'rgba(0,0,0,0.75)',
    glow: 'rgba(0,170,68,0.5)',
    sodium: '#FF6600',
    water: '#0066CC',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    en: {
      greeting: [
        'Pre-match nutrition protocol initiated.',
        "Champions fuel properly. Let's see your plan.",
        'Game day. Every macro counts.',
        'The pitch awaits. Fuel up first.',
      ],
      proteinGoalReached: [
        'GOOOOOL DE PROTEÍNA!!! 🎯',
        'Protein target achieved. Recovery confirmed.',
        'Like Ronaldo said: eat your protein.',
      ],
      calorieGoalReached: [
        'FULL TIME! Daily nutrition goal: ACHIEVED!',
        "Calorie target hit. That's a W.",
        '90 minutes of eating done. Goal scored!',
      ],
      calorieSurplus: [
        'Over the calorie line. Tactical adjustment needed.',
        'Surplus detected. Mass phase activated.',
        'Too much fuel? Channel it into training.',
      ],
      calorieDeficit: [
        'Calorie deficit. Cut phase: active.',
        'Under the target. Running lean today.',
        'Deficit noted. Stay sharp.',
      ],
      mealAdded: [
        'LOGGED! ⚽',
        'Pre-match fuel recorded.',
        'Meal entered. Macros updating.',
        'Good fuel choice.',
      ],
      streakCongrats: [
        'Unbeaten streak! Champions are consistent.',
        "Every day logged. That's a winning mentality.",
        'Clean sheet on nutrition tracking!',
      ],
      noDataYet: [
        "No fuel logged. Can't play on an empty tank.",
        'Empty diary. Log your pre-match meal.',
        'The game starts with breakfast. Log it.',
      ],
      goodMorning: [
        'Morning. Pre-training breakfast time.',
        'Rise. Fuel. Train. Repeat.',
        'Morning session fuel required.',
      ],
      goodAfternoon: [
        'Halftime. Refuel for the second half.',
        'Afternoon. Mid-match nutrition check.',
        'Post-training window. Hit that protein.',
      ],
      goodEvening: [
        'Post-match recovery meal time.',
        'Evening. Log your recovery nutrition.',
        'Final whistle. Last meal of the day.',
      ],
      goodNight: [
        'Rest. Recovery. Gains. Good night.',
        'Sleep is part of training. Rest well.',
        "Tomorrow there's another match. Rest up.",
      ],
      dashboardTitle: 'MATCH STATS',
      diaryTitle: 'NUTRITION LOG',
      progressTitle: 'PERFORMANCE',
      profileTitle: 'PLAYER PROFILE',
      settingsTitle: 'TACTICS',
      caloriesLabel: 'ENERGY',
      proteinLabel: 'PROTEIN',
      carbsLabel: 'CARBS',
      fatLabel: 'FATS',
      fiberLabel: 'FIBER',
      remainingLabel: 'REMAINING',
      consumedLabel: 'CONSUMED',
      goalLabel: 'TARGET',
      addFoodLabel: 'ADD MEAL',
      scanLabel: 'SCAN',
      searchLabel: 'SEARCH',
      macroSectionTitle: '⚽ MACRO FORMATION',
      microSectionTitle: '🔬 MICRO ANALYSIS',
      statsSectionTitle: '📊 MATCH STATS',
      mealNames: {
        BREAKFAST: 'PRE-TRAINING',
        LUNCH: 'MID-MATCH FUEL',
        DINNER: 'POST-MATCH RECOVERY',
        SNACK: 'SUBSTITUTION SNACK',
      },
    },
    'pt-BR': {
      greeting: [
        'Protocolo de nutrição pré-jogo iniciado.',
        'Campeões se alimentam direito. Vamos ver seu plano.',
        'Dia de jogo. Cada macro conta.',
        'O gramado espera. Abasteça antes.',
      ],
      proteinGoalReached: [
        'GOOOOOL DE PROTEÍNA!!! 🎯',
        'Meta de proteína alcançada. Recuperação confirmada.',
        'Como o Ronaldo dizia: coma sua proteína.',
      ],
      calorieGoalReached: [
        'FIM DE JOGO! Meta nutricional diária: ALCANÇADA!',
        'Meta de calorias batida. Isso é uma vitória.',
        '90 minutos de alimentação concluídos. Gol marcado!',
      ],
      calorieSurplus: [
        'Passou da linha de calorias. Ajuste tático necessário.',
        'Excedente detectado. Fase de massa ativada.',
        'Combustível demais? Canalize isso pro treino.',
      ],
      calorieDeficit: [
        'Déficit calórico. Fase de corte: ativa.',
        'Abaixo da meta. Correndo mais leve hoje.',
        'Déficit registrado. Fique atento.',
      ],
      mealAdded: [
        'REGISTRADO! ⚽',
        'Combustível pré-jogo registrado.',
        'Refeição inserida. Macros atualizando.',
        'Boa escolha de combustível.',
      ],
      streakCongrats: [
        'Sequência invicta! Campeões são consistentes.',
        'Todo dia registrado. Essa é a mentalidade vencedora.',
        'Sem furo no registro nutricional!',
      ],
      noDataYet: [
        'Nenhum combustível registrado. Não dá pra jogar com o tanque vazio.',
        'Diário vazio. Registre sua refeição pré-jogo.',
        'O jogo começa com o café da manhã. Registre.',
      ],
      goodMorning: [
        'Manhã. Hora do café pré-treino.',
        'Acorde. Abasteça. Treine. Repita.',
        'Combustível da sessão matinal necessário.',
      ],
      goodAfternoon: [
        'Intervalo. Reabasteça para o segundo tempo.',
        'Tarde. Checagem nutricional do meio do jogo.',
        'Janela pós-treino. Manda ver na proteína.',
      ],
      goodEvening: [
        'Hora da refeição de recuperação pós-jogo.',
        'Noite. Registre sua nutrição de recuperação.',
        'Apito final. Última refeição do dia.',
      ],
      goodNight: [
        'Descanso. Recuperação. Ganhos. Boa noite.',
        'Dormir é parte do treino. Descanse bem.',
        'Amanhã tem outro jogo. Descanse.',
      ],
      dashboardTitle: 'STATUS DA PARTIDA',
      diaryTitle: 'REGISTRO NUTRICIONAL',
      progressTitle: 'DESEMPENHO',
      profileTitle: 'PERFIL DO JOGADOR',
      settingsTitle: 'TÁTICAS',
      caloriesLabel: 'ENERGIA',
      proteinLabel: 'PROTEÍNA',
      carbsLabel: 'CARBOIDRATOS',
      fatLabel: 'GORDURAS',
      fiberLabel: 'FIBRA',
      remainingLabel: 'RESTANTE',
      consumedLabel: 'CONSUMIDO',
      goalLabel: 'ALVO',
      addFoodLabel: 'ADICIONAR REFEIÇÃO',
      scanLabel: 'ESCANEAR',
      searchLabel: 'BUSCAR',
      macroSectionTitle: '⚽ FORMAÇÃO DE MACROS',
      microSectionTitle: '🔬 MICRO ANÁLISE',
      statsSectionTitle: '📊 STATUS DA PARTIDA',
      mealNames: {
        BREAKFAST: 'PRÉ-TREINO',
        LUNCH: 'COMBUSTÍVEL DO MEIO DO JOGO',
        DINNER: 'RECUPERAÇÃO PÓS-JOGO',
        SNACK: 'LANCHE DE SUBSTITUIÇÃO',
      },
    },
  },
  companion: {
    id: 'manager',
    name: 'The Manager',
    title: {
      en: 'Tactical Nutrition Coach',
      'pt-BR': 'Técnico de Nutrição Tática',
    },
    description: {
      en: "Mastermind who optimized 3 championship-winning teams' nutrition protocols. Results only.",
      'pt-BR': 'Estrategista que otimizou os protocolos nutricionais de 3 times campeões. Só resultado importa.',
    },
    emoji: '📋',
    avatarEmoji: '⚽',
    personality: 'sporty',
    accentColor: '#00AA44',
    bubbleColor: '#102010',
    textColor: '#FFFFFF',
  },
};
