import { AppTheme } from '../types';

export const footballTheme: AppTheme = {
  id: 'football',
  name: 'football',
  displayName: 'Football',
  description: 'Fuel like a pro. The Coach is watching your macros.',
  emoji: '⚽',
  tags: ['football', 'soccer', 'sport', 'team'],
  locked: false,
  colors: {
    background: '#0A1A0A',
    surface: '#0D200D',
    surfaceElevated: '#142814',
    surfaceCard: '#102010',
    border: '#1E4A1E',
    borderLight: '#2A5E2A',
    primary: '#00AA44',
    primaryLight: '#00CC55',
    primaryDark: '#007733',
    primaryGlow: 'rgba(0,170,68,0.3)',
    secondary: '#FFD700',
    secondaryLight: '#FFE44D',
    secondaryGlow: 'rgba(255,215,0,0.2)',
    accent: '#FFFFFF',
    accentLight: '#F0F0F0',
    text: {
      primary: '#FFFFFF',
      secondary: '#99CC99',
      muted: '#336633',
      onPrimary: '#FFFFFF',
      onDark: '#FFFFFF',
    },
    macros: {
      calories: '#FF4444',
      protein: '#FFD700',
      carbs: '#00CC55',
      fat: '#FF6600',
      fiber: '#00AA44',
    },
    status: {
      success: '#00AA44',
      successLight: '#00CC55',
      warning: '#FFD700',
      warningLight: '#FFE44D',
      error: '#CC0000',
      errorLight: '#FF3333',
      info: '#0066CC',
    },
    tabBar: '#0D200D',
    tabBarActive: '#00AA44',
    tabBarInactive: '#336633',
    inputBackground: '#142814',
    inputBorder: '#1E4A1E',
    gradient: ['#0A1A0A', '#0D200D', '#0A1A0A'] as const,
    overlay: 'rgba(0,0,0,0.75)',
    glow: 'rgba(0,170,68,0.5)',
    sodium: '#FF6600',
    water: '#0066CC',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      'Pre-match nutrition protocol initiated.',
      "Champions fuel properly. Let's see your plan.",
      'Game day. Every macro counts.',
      'The pitch awaits. Fuel up first.',
    ],
    proteinGoalReached: [
      'GOOOOOL DE PROTEÍNA!!! 🎯',
      'Protein target achieved. Recovery confirmed.',
      'Like Ronaldo said: eat your protein.',
    ],
    calorieGoalReached: [
      'FULL TIME! Daily nutrition goal: ACHIEVED!',
      "Calorie target hit. That's a W.",
      '90 minutes of eating done. Goal scored!',
    ],
    calorieSurplus: [
      'Over the calorie line. Tactical adjustment needed.',
      'Surplus detected. Mass phase activated.',
      'Too much fuel? Channel it into training.',
    ],
    calorieDeficit: [
      'Calorie deficit. Cut phase: active.',
      'Under the target. Running lean today.',
      'Deficit noted. Stay sharp.',
    ],
    mealAdded: [
      'LOGGED! ⚽',
      'Pre-match fuel recorded.',
      'Meal entered. Macros updating.',
      'Good fuel choice.',
    ],
    streakCongrats: [
      "Unbeaten streak! Champions are consistent.",
      "Every day logged. That's a winning mentality.",
      'Clean sheet on nutrition tracking!',
    ],
    noDataYet: [
      "No fuel logged. Can't play on an empty tank.",
      'Empty diary. Log your pre-match meal.',
      'The game starts with breakfast. Log it.',
    ],
    goodMorning: [
      'Morning. Pre-training breakfast time.',
      'Rise. Fuel. Train. Repeat.',
      'Morning session fuel required.',
    ],
    goodAfternoon: [
      'Halftime. Refuel for the second half.',
      'Afternoon. Mid-match nutrition check.',
      'Post-training window. Hit that protein.',
    ],
    goodEvening: [
      'Post-match recovery meal time.',
      'Evening. Log your recovery nutrition.',
      'Final whistle. Last meal of the day.',
    ],
    goodNight: [
      'Rest. Recovery. Gains. Good night.',
      'Sleep is part of training. Rest well.',
      "Tomorrow there's another match. Rest up.",
    ],
    dashboardTitle: 'MATCH STATS',
    diaryTitle: 'NUTRITION LOG',
    progressTitle: 'PERFORMANCE',
    profileTitle: 'PLAYER PROFILE',
    settingsTitle: 'TACTICS',
    caloriesLabel: 'ENERGY',
    proteinLabel: 'PROTEIN',
    carbsLabel: 'CARBS',
    fatLabel: 'FATS',
    fiberLabel: 'FIBER',
    remainingLabel: 'REMAINING',
    consumedLabel: 'CONSUMED',
    goalLabel: 'TARGET',
    addFoodLabel: 'ADD MEAL',
    scanLabel: 'SCAN',
    searchLabel: 'SEARCH',
    macroSectionTitle: '⚽ MACRO FORMATION',
    microSectionTitle: '🔬 MICRO ANALYSIS',
    statsSectionTitle: '📊 MATCH STATS',
    mealNames: {
      BREAKFAST: 'PRE-TRAINING',
      LUNCH: 'MID-MATCH FUEL',
      DINNER: 'POST-MATCH RECOVERY',
      SNACK: 'SUBSTITUTION SNACK',
    },
  },
  companion: {
    id: 'manager',
    name: 'The Manager',
    title: 'Tactical Nutrition Coach',
    description: "Mastermind who optimized 3 championship-winning teams' nutrition protocols. Results only.",
    emoji: '📋',
    avatarEmoji: '⚽',
    personality: 'sporty',
    accentColor: '#00AA44',
    bubbleColor: '#102010',
    textColor: '#FFFFFF',
  },
};
