import { AppTheme } from '../types';

export const cyberpunkTheme: AppTheme = {
  id: 'cyberpunk',
  name: 'cyberpunk',
  displayName: 'Cyberpunk',
  description: 'Biometric tracking in the neon dystopia. ARIA-7 optimizes your macros.',
  emoji: '🤖',
  tags: ['neon', 'tech', 'futuristic'],
  locked: false,
  colors: {
    background: '#080B12',
    surface: '#0D1117',
    surfaceElevated: '#111820',
    surfaceCard: '#0F1520',
    border: '#00F5FF33',
    borderLight: '#00F5FF55',
    primary: '#00F5FF',
    primaryLight: '#40FFFF',
    primaryDark: '#008899',
    primaryGlow: 'rgba(0,245,255,0.3)',
    secondary: '#FF2D9B',
    secondaryLight: '#FF6BBF',
    secondaryGlow: 'rgba(255,45,155,0.25)',
    accent: '#7B2FFF',
    accentLight: '#A855FF',
    text: {
      primary: '#E0F7FA',
      secondary: '#80CBC4',
      muted: '#37474F',
      onPrimary: '#080B12',
      onDark: '#E0F7FA',
    },
    macros: {
      calories: '#FF2D9B',
      protein: '#00F5FF',
      carbs: '#7B2FFF',
      fat: '#FFD600',
      fiber: '#00E676',
    },
    status: {
      success: '#00E676',
      successLight: '#69F0AE',
      warning: '#FFD600',
      warningLight: '#FFEA00',
      error: '#FF1744',
      errorLight: '#FF6E6E',
      info: '#00B0FF',
    },
    tabBar: '#0D1117',
    tabBarActive: '#00F5FF',
    tabBarInactive: '#37474F',
    inputBackground: '#0D1117',
    inputBorder: '#00F5FF33',
    gradient: ['#080B12', '#0D1520', '#080B12'] as const,
    overlay: 'rgba(0,0,0,0.8)',
    glow: 'rgba(0,245,255,0.5)',
    sodium: '#FF6D00',
    water: '#00B0FF',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      'System online. Awaiting dietary input.',
      'Biometrics scanning... Good morning, user.',
      'Neural interface connected. Log your fuel.',
      'ARIA-7 online. Macro optimization ready.',
    ],
    proteinGoalReached: [
      'PROTEIN.EXE COMPLETE. Muscle synthesis protocol initiated.',
      'Amino acid quota reached. Cellular repair engaged.',
      'Target protein achieved. System performance: OPTIMAL.',
    ],
    calorieGoalReached: [
      'Daily energy allocation consumed. Neural pathways optimized.',
      'Caloric parameters met. System efficiency: 100%.',
      'Energy quota fulfilled. Standby for recovery protocol.',
    ],
    calorieSurplus: [
      'Warning: Energy surplus detected. Bulking protocol active.',
      'Caloric overflow. Redirecting to muscle synthesis.',
      'Excess energy stored. Mass gain sequence initiated.',
    ],
    calorieDeficit: [
      'Deficit protocol active. Fat burn sequence running.',
      'Energy shortage detected. Accessing stored reserves.',
      'Cutting phase engaged. Body recomposition in progress.',
    ],
    mealAdded: [
      'Data logged.',
      'Nutritional data uploaded.',
      'Entry confirmed. Database updated.',
      'Macro tracking: active.',
    ],
    streakCongrats: [
      'Consistency metrics: EXCEPTIONAL.',
      'Streak protocol maintained. Neural adaptation confirmed.',
      'Continuous logging detected. Habit formation: SUCCESS.',
    ],
    noDataYet: [
      'No nutritional data detected. Initialize logging sequence.',
      'Database empty. Begin data entry protocol.',
      'Awaiting first input. System ready.',
    ],
    goodMorning: [
      'Good morning. Daily protocols initializing.',
      'System boot complete. Morning fuel required.',
      'Rise and optimize. ARIA-7 ready.',
    ],
    goodAfternoon: [
      'Midday checkpoint. Macro status nominal.',
      'Afternoon systems check. Log your fuel.',
      'PM cycle active. Continue optimization.',
    ],
    goodEvening: [
      'Evening wind-down initiated. Final macros pending.',
      'Day nearly complete. Log remaining fuel.',
      'Evening protocol active.',
    ],
    goodNight: [
      'Sleep protocol initiated. Recovery in progress.',
      'System entering low-power mode. Good night.',
      'Overnight recovery sequence active.',
    ],
    dashboardTitle: 'DASHBOARD',
    diaryTitle: 'DATA LOG',
    progressTitle: 'METRICS',
    profileTitle: 'USER PROFILE',
    settingsTitle: 'SYSTEM CONFIG',
    caloriesLabel: 'ENERGY (kcal)',
    proteinLabel: 'PROTEIN',
    carbsLabel: 'CARBOHYDRATES',
    fatLabel: 'LIPIDS',
    fiberLabel: 'FIBER',
    remainingLabel: 'REMAINING QUOTA',
    consumedLabel: 'CONSUMED',
    goalLabel: 'TARGET',
    addFoodLabel: 'ADD DATA',
    scanLabel: 'SCAN UPC',
    searchLabel: 'SEARCH DATABASE',
    macroSectionTitle: '⚡ MACRO MATRIX',
    microSectionTitle: '🔬 MICRONUTRIENT SCAN',
    statsSectionTitle: '📊 PERFORMANCE METRICS',
    mealNames: {
      BREAKFAST: 'MORNING FUEL',
      LUNCH: 'MIDDAY UPLOAD',
      DINNER: 'EVENING RATION',
      SNACK: 'QUICK RELOAD',
    },
  },
  companion: {
    id: 'aria7',
    name: 'ARIA-7',
    title: 'Holographic Nutrition AI',
    description: 'Advanced AI optimized for human performance tracking and macro analysis.',
    emoji: '🤖',
    avatarEmoji: '💠',
    personality: 'tech',
    accentColor: '#00F5FF',
    bubbleColor: '#0D1520',
    textColor: '#E0F7FA',
  },
};
