import { AppThemeDefinition } from '../types';

export const animeTheme: AppThemeDefinition = {
  id: 'anime',
  name: 'anime',
  displayName: 'ANIME MODE',
  description: {
    en: 'POWER LEVEL INCREASING!!! Train like a shonen protagonist.',
    'pt-BR': 'PODER AUMENTANDO!!! Treine como um protagonista de shonen.',
  },
  emoji: '🔥',
  dashboardIcon: 'flame',
  tags: ['anime', 'shonen', 'energy', 'intense'],
  locked: false,
  colors: {
    background: '#0A0510',
    surface: '#140B20',
    surfaceElevated: '#1E1030',
    surfaceCard: '#180D28',
    border: '#FF6B0033',
    borderLight: '#FF6B0066',
    primary: '#FF6B00',
    primaryLight: '#FF9500',
    primaryDark: '#CC4A00',
    primaryGlow: 'rgba(255,107,0,0.4)',
    secondary: '#0066FF',
    secondaryLight: '#4D99FF',
    secondaryGlow: 'rgba(0,102,255,0.3)',
    accent: '#FFD700',
    accentLight: '#FFE866',
    text: {
      primary: '#FFF5E6',
      secondary: '#FFB366',
      muted: '#663300',
      onPrimary: '#0A0510',
      onDark: '#FFF5E6',
    },
    macros: {
      calories: '#FF6B00',
      protein: '#FF2D9B',
      carbs: '#FFD700',
      fat: '#9B59B6',
      fiber: '#00E676',
    },
    status: {
      success: '#00E676',
      successLight: '#69F0AE',
      warning: '#FFD700',
      warningLight: '#FFE866',
      error: '#FF1744',
      errorLight: '#FF6E6E',
      info: '#0066FF',
    },
    tabBar: '#140B20',
    tabBarActive: '#FF6B00',
    tabBarInactive: '#663300',
    inputBackground: '#1E1030',
    inputBorder: '#FF6B0033',
    gradient: ['#0A0510', '#1A0A00', '#0A0510'] as const,
    overlay: 'rgba(0,0,0,0.75)',
    glow: 'rgba(255,107,0,0.6)',
    sodium: '#FF6D00',
    water: '#0066FF',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    en: {
      greeting: [
        'NANIII!!! The hero has arrived!',
        "IT'S TIME TO GET STRONG!!!",
        'YOUR TRAINING BEGINS NOW, CHAMPION!!!',
        'BELIEVE IN YOUR GAINS!!!',
      ],
      proteinGoalReached: [
        'PROTEIN LEVEL OVER 9000!!!',
        'POWER INCREASING!!! MUSCLE GROWTH CONFIRMED!!!',
        'PLUS ULTRA!!! PROTEIN GOAL SMASHED!!!',
      ],
      calorieGoalReached: [
        "TODAY'S TRAINING IS COMPLETE! Power +100!",
        'CALORIE GOAL ACHIEVED!!! THE CROWD GOES WILD!!!',
        'VICTORYYYY!!! YOU DID IT CHAMPION!!!',
      ],
      calorieSurplus: [
        'BULKING ARC ACTIVATED!!! GET HUGE!!!',
        "EATING BIG = GETTING BIG!!! LET'S GOOO!!!",
        'THE POWER OF SURPLUS FILLS YOUR MUSCLES!!!',
      ],
      calorieDeficit: [
        'CUTTING ARC! TRUE POWER THROUGH RESTRAINT!!!',
        'THE HERO TRAINS THROUGH HUNGER!!!',
        'LEAN AND MEAN! THE SHREDDING BEGINS!!!',
      ],
      mealAdded: [
        'FUEL CONSUMED!!! POWER UP!!!',
        'NOURISHMENT LOGGED!!! LEVEL UP!',
        'MEAL ADDED!!! THE GAINS GROW!!!',
        'ITADAKIMASU!!! LOGGED!!!',
      ],
      streakCongrats: [
        'CONSISTENCY IS THE POWER OF THE TRUE HERO!!!',
        'STREAK MAINTAINED!!! LEGENDARY STATUS!!!',
        "YOU HAVEN'T SKIPPED A DAY!!! ABSOLUTE UNIT!!!",
      ],
      noDataYet: [
        "THE HERO'S JOURNEY HAS NOT BEGUN!!! LOG SOMETHING!!!",
        "EMPTY LOG?! THE VILLAIN WINS IF YOU DON'T EAT!!!",
        'START YOUR TRAINING ARC!!! LOG YOUR FIRST MEAL!!!',
      ],
      goodMorning: [
        'RISE AND GRIND!!! MORNING FUEL TIME!!!',
        "NEW DAY! NEW GAINS! LET'S GOOOOO!!!",
        'THE SUN RISES ON A NEW TRAINING ARC!!!',
      ],
      goodAfternoon: [
        'MIDDAY POWER UP REQUIRED!!!',
        'AFTERNOON TRAINING FUEL LOADING!!!',
        "KEEP GOING CHAMPION! YOU'RE HALFWAY THERE!!!",
      ],
      goodEvening: [
        'EVENING MEAL!!! RECOVERY MODE ACTIVATE!!!',
        'DINNER TIME!!! REFUEL THE HERO!!!',
        'ALMOST DONE FOR TODAY!!! FINAL FUEL!!!',
      ],
      goodNight: [
        'REST UP! MUSCLES GROW WHILE YOU SLEEP!!!',
        'SLEEP = GAINS!!! GOOD NIGHT CHAMPION!!!',
        'RECOVERY ARC INITIATED!!! SEE YOU TOMORROW!!!',
      ],
      dashboardTitle: 'POWER LEVEL',
      diaryTitle: 'TRAINING LOG',
      progressTitle: 'POWER SCALING',
      profileTitle: 'HERO STATS',
      settingsTitle: 'ABILITIES',
      caloriesLabel: 'ENERGY (kcal)',
      proteinLabel: 'MUSCLE FUEL',
      carbsLabel: 'POWER CARBS',
      fatLabel: 'ENERGY RESERVES',
      fiberLabel: 'FIBER FORCE',
      remainingLabel: 'POWER REMAINING',
      consumedLabel: 'CONSUMED',
      goalLabel: 'DAILY MISSION',
      addFoodLabel: 'ADD FUEL',
      scanLabel: 'SCAN POWER ITEM',
      searchLabel: 'FIND POWER FOOD',
      macroSectionTitle: '💪 MACRO POWER STATS',
      microSectionTitle: '⚡ MICRO ABILITIES',
      statsSectionTitle: '🏆 BATTLE RECORDS',
      mealNames: {
        BREAKFAST: 'MORNING TRAINING FUEL',
        LUNCH: 'MIDDAY POWER MEAL',
        DINNER: 'RECOVERY FEAST',
        SNACK: 'QUICK POWER SNACK',
      },
    },
    'pt-BR': {
      greeting: [
        'NANIII!!! O herói chegou!',
        'CHEGOU A HORA DE FICAR FORTE!!!',
        'SEU TREINAMENTO COMEÇA AGORA, CAMPEÃO!!!',
        'ACREDITE NOS SEUS GANHOS!!!',
      ],
      proteinGoalReached: [
        'NÍVEL DE PROTEÍNA ACIMA DE 9000!!!',
        'PODER AUMENTANDO!!! CRESCIMENTO MUSCULAR CONFIRMADO!!!',
        'PLUS ULTRA!!! META DE PROTEÍNA ESMAGADA!!!',
      ],
      calorieGoalReached: [
        'TREINO DE HOJE COMPLETO! Poder +100!',
        'META DE CALORIAS ALCANÇADA!!! A PLATEIA VAI À LOUCURA!!!',
        'VITÓRIAAA!!! VOCÊ CONSEGUIU, CAMPEÃO!!!',
      ],
      calorieSurplus: [
        'ARCO DE BULKING ATIVADO!!! FIQUE ENORME!!!',
        'COMER MUITO = FICAR GRANDE!!! VAMOOOS!!!',
        'O PODER DO EXCEDENTE PREENCHE SEUS MÚSCULOS!!!',
      ],
      calorieDeficit: [
        'ARCO DE CORTE! VERDADEIRO PODER PELA DISCIPLINA!!!',
        'O HERÓI TREINA MESMO COM FOME!!!',
        'MAGRO E FEROZ! O DEFINIÇÃO COMEÇA!!!',
      ],
      mealAdded: [
        'COMBUSTÍVEL CONSUMIDO!!! POWER UP!!!',
        'NUTRIÇÃO REGISTRADA!!! LEVEL UP!',
        'REFEIÇÃO ADICIONADA!!! OS GANHOS CRESCEM!!!',
        'ITADAKIMASU!!! REGISTRADO!!!',
      ],
      streakCongrats: [
        'CONSISTÊNCIA É O PODER DO VERDADEIRO HERÓI!!!',
        'SEQUÊNCIA MANTIDA!!! STATUS LENDÁRIO!!!',
        'VOCÊ NÃO PULOU NENHUM DIA!!! UNIDADE ABSOLUTA!!!',
      ],
      noDataYet: [
        'A JORNADA DO HERÓI AINDA NÃO COMEÇOU!!! REGISTRE ALGO!!!',
        'REGISTRO VAZIO?! O VILÃO VENCE SE VOCÊ NÃO COMER!!!',
        'COMECE SEU ARCO DE TREINO!!! REGISTRE SUA PRIMEIRA REFEIÇÃO!!!',
      ],
      goodMorning: [
        'ACORDE E TREINE!!! HORA DO COMBUSTÍVEL MATINAL!!!',
        'NOVO DIA! NOVOS GANHOS! VAMOOOOS!!!',
        'O SOL NASCE EM UM NOVO ARCO DE TREINO!!!',
      ],
      goodAfternoon: [
        'POWER UP DO MEIO-DIA NECESSÁRIO!!!',
        'CARREGANDO COMBUSTÍVEL DE TREINO DA TARDE!!!',
        'CONTINUE, CAMPEÃO! VOCÊ ESTÁ NA METADE!!!',
      ],
      goodEvening: [
        'REFEIÇÃO NOTURNA!!! MODO RECUPERAÇÃO ATIVADO!!!',
        'HORA DO JANTAR!!! REABASTEÇA O HERÓI!!!',
        'QUASE TERMINANDO HOJE!!! COMBUSTÍVEL FINAL!!!',
      ],
      goodNight: [
        'DESCANSE! OS MÚSCULOS CRESCEM ENQUANTO VOCÊ DORME!!!',
        'DORMIR = GANHOS!!! BOA NOITE, CAMPEÃO!!!',
        'ARCO DE RECUPERAÇÃO INICIADO!!! ATÉ AMANHÃ!!!',
      ],
      dashboardTitle: 'NÍVEL DE PODER',
      diaryTitle: 'REGISTRO DE TREINO',
      progressTitle: 'EVOLUÇÃO DE PODER',
      profileTitle: 'STATUS DO HERÓI',
      settingsTitle: 'HABILIDADES',
      caloriesLabel: 'ENERGIA (kcal)',
      proteinLabel: 'COMBUSTÍVEL MUSCULAR',
      carbsLabel: 'CARBOS DE PODER',
      fatLabel: 'RESERVAS DE ENERGIA',
      fiberLabel: 'FORÇA DE FIBRA',
      remainingLabel: 'PODER RESTANTE',
      consumedLabel: 'CONSUMIDO',
      goalLabel: 'MISSÃO DIÁRIA',
      addFoodLabel: 'ADICIONAR COMBUSTÍVEL',
      scanLabel: 'ESCANEAR ITEM DE PODER',
      searchLabel: 'ENCONTRAR COMIDA DE PODER',
      macroSectionTitle: '💪 STATUS DE MACRO PODER',
      microSectionTitle: '⚡ MICRO HABILIDADES',
      statsSectionTitle: '🏆 RECORDES DE BATALHA',
      mealNames: {
        BREAKFAST: 'COMBUSTÍVEL DE TREINO MATINAL',
        LUNCH: 'REFEIÇÃO DE PODER DO MEIO-DIA',
        DINNER: 'FESTIM DE RECUPERAÇÃO',
        SNACK: 'LANCHE RÁPIDO DE PODER',
      },
    },
  },
  companion: {
    id: 'toguro',
    name: 'Toguro Sensei',
    title: {
      en: 'The Eternal Trainer',
      'pt-BR': 'O Treinador Eterno',
    },
    description: {
      en: 'An ancient warrior who achieved immortality through perfect macros. His gaze alone adds 10kg to your lifts.',
      'pt-BR': 'Um guerreiro ancestral que alcançou a imortalidade através de macros perfeitos. Seu olhar sozinho adiciona 10kg aos seus levantamentos.',
    },
    emoji: '💪',
    avatarEmoji: '🥊',
    personality: 'anime',
    accentColor: '#FF6B00',
    bubbleColor: '#180D28',
    textColor: '#FFF5E6',
  },
};
