import { AppTheme } from '../types';

export const animeTheme: AppTheme = {
  id: 'anime',
  name: 'anime',
  displayName: 'ANIME MODE',
  description: 'POWER LEVEL INCREASING!!! Train like a shonen protagonist.',
  emoji: '🔥',
  tags: ['anime', 'shonen', 'energy', 'intense'],
  locked: false,
  colors: {
    background: '#0A0510',
    surface: '#140B20',
    surfaceElevated: '#1E1030',
    surfaceCard: '#180D28',
    border: '#FF6B0033',
    borderLight: '#FF6B0066',
    primary: '#FF6B00',
    primaryLight: '#FF9500',
    primaryDark: '#CC4A00',
    primaryGlow: 'rgba(255,107,0,0.4)',
    secondary: '#0066FF',
    secondaryLight: '#4D99FF',
    secondaryGlow: 'rgba(0,102,255,0.3)',
    accent: '#FFD700',
    accentLight: '#FFE866',
    text: {
      primary: '#FFF5E6',
      secondary: '#FFB366',
      muted: '#663300',
      onPrimary: '#0A0510',
      onDark: '#FFF5E6',
    },
    macros: {
      calories: '#FF6B00',
      protein: '#FF2D9B',
      carbs: '#FFD700',
      fat: '#9B59B6',
      fiber: '#00E676',
    },
    status: {
      success: '#00E676',
      successLight: '#69F0AE',
      warning: '#FFD700',
      warningLight: '#FFE866',
      error: '#FF1744',
      errorLight: '#FF6E6E',
      info: '#0066FF',
    },
    tabBar: '#140B20',
    tabBarActive: '#FF6B00',
    tabBarInactive: '#663300',
    inputBackground: '#1E1030',
    inputBorder: '#FF6B0033',
    gradient: ['#0A0510', '#1A0A00', '#0A0510'] as const,
    overlay: 'rgba(0,0,0,0.75)',
    glow: 'rgba(255,107,0,0.6)',
    sodium: '#FF6D00',
    water: '#0066FF',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      'NANIII!!! The hero has arrived!',
      "IT'S TIME TO GET STRONG!!!",
      'YOUR TRAINING BEGINS NOW, CHAMPION!!!',
      'BELIEVE IN YOUR GAINS!!!',
    ],
    proteinGoalReached: [
      'PROTEIN LEVEL OVER 9000!!!',
      'POWER INCREASING!!! MUSCLE GROWTH CONFIRMED!!!',
      'PLUS ULTRA!!! PROTEIN GOAL SMASHED!!!',
    ],
    calorieGoalReached: [
      "TODAY'S TRAINING IS COMPLETE! Power +100!",
      'CALORIE GOAL ACHIEVED!!! THE CROWD GOES WILD!!!',
      'VICTORYYYY!!! YOU DID IT CHAMPION!!!',
    ],
    calorieSurplus: [
      'BULKING ARC ACTIVATED!!! GET HUGE!!!',
      "EATING BIG = GETTING BIG!!! LET'S GOOO!!!",
      'THE POWER OF SURPLUS FILLS YOUR MUSCLES!!!',
    ],
    calorieDeficit: [
      'CUTTING ARC! TRUE POWER THROUGH RESTRAINT!!!',
      'THE HERO TRAINS THROUGH HUNGER!!!',
      'LEAN AND MEAN! THE SHREDDING BEGINS!!!',
    ],
    mealAdded: [
      'FUEL CONSUMED!!! POWER UP!!!',
      'NOURISHMENT LOGGED!!! LEVEL UP!',
      'MEAL ADDED!!! THE GAINS GROW!!!',
      'ITADAKIMASU!!! LOGGED!!!',
    ],
    streakCongrats: [
      'CONSISTENCY IS THE POWER OF THE TRUE HERO!!!',
      'STREAK MAINTAINED!!! LEGENDARY STATUS!!!',
      "YOU HAVEN'T SKIPPED A DAY!!! ABSOLUTE UNIT!!!",
    ],
    noDataYet: [
      "THE HERO'S JOURNEY HAS NOT BEGUN!!! LOG SOMETHING!!!",
      "EMPTY LOG?! THE VILLAIN WINS IF YOU DON'T EAT!!!",
      'START YOUR TRAINING ARC!!! LOG YOUR FIRST MEAL!!!',
    ],
    goodMorning: [
      'RISE AND GRIND!!! MORNING FUEL TIME!!!',
      "NEW DAY! NEW GAINS! LET'S GOOOOO!!!",
      'THE SUN RISES ON A NEW TRAINING ARC!!!',
    ],
    goodAfternoon: [
      'MIDDAY POWER UP REQUIRED!!!',
      'AFTERNOON TRAINING FUEL LOADING!!!',
      "KEEP GOING CHAMPION! YOU'RE HALFWAY THERE!!!",
    ],
    goodEvening: [
      'EVENING MEAL!!! RECOVERY MODE ACTIVATE!!!',
      'DINNER TIME!!! REFUEL THE HERO!!!',
      'ALMOST DONE FOR TODAY!!! FINAL FUEL!!!',
    ],
    goodNight: [
      'REST UP! MUSCLES GROW WHILE YOU SLEEP!!!',
      'SLEEP = GAINS!!! GOOD NIGHT CHAMPION!!!',
      'RECOVERY ARC INITIATED!!! SEE YOU TOMORROW!!!',
    ],
    dashboardTitle: 'POWER LEVEL',
    diaryTitle: 'TRAINING LOG',
    progressTitle: 'POWER SCALING',
    profileTitle: 'HERO STATS',
    settingsTitle: 'ABILITIES',
    caloriesLabel: 'ENERGY (kcal)',
    proteinLabel: 'MUSCLE FUEL',
    carbsLabel: 'POWER CARBS',
    fatLabel: 'ENERGY RESERVES',
    fiberLabel: 'FIBER FORCE',
    remainingLabel: 'POWER REMAINING',
    consumedLabel: 'CONSUMED',
    goalLabel: 'DAILY MISSION',
    addFoodLabel: 'ADD FUEL',
    scanLabel: 'SCAN POWER ITEM',
    searchLabel: 'FIND POWER FOOD',
    macroSectionTitle: '💪 MACRO POWER STATS',
    microSectionTitle: '⚡ MICRO ABILITIES',
    statsSectionTitle: '🏆 BATTLE RECORDS',
    mealNames: {
      BREAKFAST: 'MORNING TRAINING FUEL',
      LUNCH: 'MIDDAY POWER MEAL',
      DINNER: 'RECOVERY FEAST',
      SNACK: 'QUICK POWER SNACK',
    },
  },
  companion: {
    id: 'toguro',
    name: 'Toguro Sensei',
    title: 'The Eternal Trainer',
    description: 'An ancient warrior who achieved immortality through perfect macros. His gaze alone adds 10kg to your lifts.',
    emoji: '💪',
    avatarEmoji: '🥊',
    personality: 'anime',
    accentColor: '#FF6B00',
    bubbleColor: '#180D28',
    textColor: '#FFF5E6',
  },
};
