import { AppTheme } from '../types';

export const cleanTheme: AppTheme = {
  id: 'clean',
  name: 'clean',
  displayName: 'Clean',
  description: 'Minimal and focused. Clear data, clear mind.',
  emoji: '✨',
  tags: ['minimal', 'clean', 'light', 'saas'],
  locked: false,
  colors: {
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    surfaceCard: '#FFFFFF',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    primary: '#0EA5E9',
    primaryLight: '#38BDF8',
    primaryDark: '#0284C7',
    primaryGlow: 'rgba(14,165,233,0.2)',
    secondary: '#10B981',
    secondaryLight: '#34D399',
    secondaryGlow: 'rgba(16,185,129,0.2)',
    accent: '#8B5CF6',
    accentLight: '#A78BFA',
    text: {
      primary: '#0F172A',
      secondary: '#475569',
      muted: '#94A3B8',
      onPrimary: '#FFFFFF',
      onDark: '#FFFFFF',
    },
    macros: {
      calories: '#EF4444',
      protein: '#8B5CF6',
      carbs: '#F59E0B',
      fat: '#0EA5E9',
      fiber: '#10B981',
    },
    status: {
      success: '#10B981',
      successLight: '#34D399',
      warning: '#F59E0B',
      warningLight: '#FCD34D',
      error: '#EF4444',
      errorLight: '#FCA5A5',
      info: '#0EA5E9',
    },
    tabBar: '#FFFFFF',
    tabBarActive: '#0EA5E9',
    tabBarInactive: '#94A3B8',
    inputBackground: '#F8FAFC',
    inputBorder: '#E2E8F0',
    gradient: ['#F8FAFC', '#EFF6FF', '#F8FAFC'] as const,
    overlay: 'rgba(15,23,42,0.5)',
    glow: 'rgba(14,165,233,0.3)',
    sodium: '#F97316',
    water: '#0EA5E9',
    white: '#FFFFFF',
    transparent: 'transparent',
  },
  messages: {
    greeting: [
      'Good to see you! Ready to track?',
      "Let's make today count.",
      'Your nutrition journey continues.',
      'Time to log your meals!',
    ],
    proteinGoalReached: [
      'Protein goal reached. Great work!',
      'You hit your protein target today!',
      'Excellent! Muscle recovery is on track.',
    ],
    calorieGoalReached: [
      'Calorie goal achieved for today.',
      "You've hit your daily target. Nice job!",
      'Daily nutrition goal complete!',
    ],
    calorieSurplus: [
      "You're over your calorie goal today.",
      'Calorie surplus noted. Adjust tomorrow if needed.',
      'Over goal. Consider lighter meals next time.',
    ],
    calorieDeficit: [
      "You're under your calorie goal today.",
      'Calorie deficit — great for weight loss goals.',
      "You're in a deficit. Stay consistent!",
    ],
    mealAdded: [
      'Logged!',
      'Meal added.',
      'Saved successfully.',
      'Entry recorded.',
    ],
    streakCongrats: [
      "You're on a streak! Keep it up!",
      'Consistency is key — great job!',
      'Another day logged. Excellent habit!',
    ],
    noDataYet: [
      'No meals logged yet. Start tracking!',
      'Ready to log your first meal?',
      'Your diary is empty. Add your first meal!',
    ],
    goodMorning: [
      'Good morning! Start your day right.',
      'Morning! Time for breakfast.',
      'Rise and shine! Log your breakfast.',
    ],
    goodAfternoon: [
      "Good afternoon! How's lunch looking?",
      'Midday check-in. How are your macros?',
      'Afternoon! Keep up the good work.',
    ],
    goodEvening: [
      'Good evening! Wrapping up for the day?',
      'Almost done for the day. Log dinner!',
      "Evening! Don't forget your final meal.",
    ],
    goodNight: [
      'Good night! Rest up.',
      'Time to recover. See you tomorrow!',
      'Great day of tracking. Sleep well!',
    ],
    dashboardTitle: 'Dashboard',
    diaryTitle: 'Food Diary',
    progressTitle: 'Progress',
    profileTitle: 'Profile',
    settingsTitle: 'Settings',
    caloriesLabel: 'Calories',
    proteinLabel: 'Protein',
    carbsLabel: 'Carbs',
    fatLabel: 'Fat',
    fiberLabel: 'Fiber',
    remainingLabel: 'Remaining',
    consumedLabel: 'Consumed',
    goalLabel: 'Goal',
    addFoodLabel: 'Add Food',
    scanLabel: 'Scan Barcode',
    searchLabel: 'Search Foods',
    macroSectionTitle: '📊 Macros',
    microSectionTitle: '🔬 Micronutrients',
    statsSectionTitle: '📈 Daily Stats',
    mealNames: {
      BREAKFAST: 'Breakfast',
      LUNCH: 'Lunch',
      DINNER: 'Dinner',
      SNACK: 'Snack',
    },
  },
  companion: {
    id: 'alex',
    name: 'Alex',
    title: 'Your Nutrition Coach',
    description: 'Friendly, evidence-based nutrition coach. No nonsense, just results.',
    emoji: '👋',
    avatarEmoji: '🥗',
    personality: 'clean',
    accentColor: '#0EA5E9',
    bubbleColor: '#EFF6FF',
    textColor: '#0F172A',
  },
};
